### ISSUE TITLE
Can't use + on Amount

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/as#272] opened 2023-06-28 15:49 UTC
**Describe the bug**
Can't use + operator on amount

**To Reproduce**

1. Write a SC like this : 
```
  let cost = new Amount(0);
  cost = cost + new Amount(1)
```

**Expected behavior**
Working

**Thyra version**
Don't using thyra

**Additional context**
Error seems to say that it's because you return a result with your add

**Comment by julienbrs** [comment] 2023-07-04 13:26
@AurelienFT I'll close this issue, it is an intended behaviour as explained by Gregory here https://github.com/massalabs/as/pull/273#pullrequestreview-1506663746

**Comment by AurelienFT** [comment] 2023-07-04 14:14
> @AurelienFT I'll close this issue if it's ok for you, it is an intended behaviour as explained by Gregory here [#273 (review)](https://github.com/massalabs/as/pull/273#pullrequestreview-1506663746)

I don't think it's the intended behavior I understand the comment of Gregory but if it's possible to use the + with a result I think you should document it because it's not intuitive at all and if it's not possible because to work it shouldn't return a result then I think you should remove the override of `+` so that we understand it's not possible

**Comment by Ben-Rey** [comment] 2023-07-05 08:29
![Screenshot 2023-07-05 at 10 17 31](https://github.com/massalabs/as/assets/44082144/5bdee28e-86cc-4f7a-92e5-9700fbec80c6)

This code compile, but it's not intuitive and it displays an error message in the IDE. 
I agree with Aurelien, we should remove the ability to use the "+" operator on objects like the amount, as it's confusing.

It would have been nice only if we were able to return an Amount.

**Closed** 2024-02-19 10:10 UTC
